//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Part
    {
        public int PartId { get; set; }
        public string PartNumber { get; set; }
        public string PartDescription { get; set; }
        public decimal PartCost { get; set; }
        public int PartQOH { get; set; }
        public Nullable<decimal> PartTotalValue { get; set; }
        public string PartNote { get; set; }
        public System.DateTime LastUpdatedOn { get; set; }
        public string PartType { get; set; }
    }
}
